TURSO_AUTH_TOKEN="eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTcxNjczNDAsImlkIjoiMmU5YzlkNTAtNmFkOS00YjRjLWEwYTUtNjM5NzBjYTBmMDJjIiwicmlkIjoiN2FiOGFmY2MtNDg1YS00MWI1LWFhZjQtZjY5YmE3MGY4NGNjIn0.1WYuRU6DSDuMRzt0_1Mha5vVd3MyQgZ_Ofb7O3sP7qfFCk96Mba8BhLEUQ0XVNCWg9Az-_zTnhuSh0PH0ozrCA"
TURSO_DATABASE_URL="libsql://database-indigo-elephant-vercel-icfg-eartvzygjqa0c1mshlit8uak.aws-us-east-1.turso.io"

# Use Turso for all environments
DATABASE_URL="libsql://database-indigo-elephant-vercel-icfg-eartvzygjqa0c1mshlit8uak.aws-us-east-1.turso.io"

# Authentication
AUTH_USERNAME="admin"
AUTH_PASSWORD="UU3TPAj0ypbfvD1QBb39"
SESSION_SECRET="jjhZRwCa69Za1YrFsD96"